screen:
  fps: 30
  quality: 90
  alpha: 15
  width: 1920
  height: 1280
  tosbs: false
  cursor: false
  fullscreen: false
rtmp:
  push: "rtmp://127.0.0.1:1935/live/{{.channelkey}}"
  key: "http://localhost:8090/control/get?room={{.channel}}"
ffmpeg:
  bin: "d:\\pf\\ffmpeg\\bin\\ffmpeg"
flv:
  dir: "data"
